@startuml
class Phone{
    -type : State
}

class State{
+typeState() : string
+pressButton()
}
note right of State: chacune de ses variables lance des exceptions
class OffState extends State{
+typeState() : string
+pressButton()
}
class OnState extends State{
+typeState() : string
+pressButton()
}
class PlugState extends State{
+typeState() : string
+pressButton()
}

Phone -> State : est un état
OnState<.left.>OffState

@enduml